### ISSUE TITLE
内存不释放？没有发现情况

### ISSUE THREAD

**Issue by fengyun911** [Bonway/BBGestureBack#10]
调用系统返回可以将页面释放，调用手势返回 部分页面无法释放

**Comment by Bonway** [comment]
没有的，我是释放的，你再看看，是不是 你自身页面循环引用了，导致的 无法释放？

**Comment by fengyun911** [comment]
我调用系统的返回事件是可以的

**Comment by Bonway** [comment]
发现您问题比较多，方便的话，留下微信或者QQ，我加你一下，一起解决下！

**Comment by Bonway** [comment]
用普通的dealloc、instrument中leaks、和三方工具 MLeaksFinder、PLeakSniffer 检查了，没有发现内存泄漏，不释放的问题，方便的话，留下微信或者QQ，我加你一下，一起解决下！
