### ISSUE TITLE
页面截图一闪而过

### ISSUE THREAD

**Issue by RaidenLin** [Bonway/BBGestureBack#13]
从根控制器push到A，再从A push到B，之后从B pop到A，再从A pop到根控制器的时候，会闪一下A页面截图，一开始以为是我集成的问题，后来发现再你的demo中添加一个B，也有这个问题，这个是什么原因呢，测试系统为iOS 13

**Comment by RaidenLin** [comment]
已发现问题所在，BBNavigationController.m中的arrayScreenshot并没有初始化，致使其始终为nil，只需要在本页面的viewDidLoad方法中添加self.arrayScreenshot = [NSMutableArray array];即可，使其遵循遵循autoreleasepool机制。

**Comment by Bonway** [comment]
谢谢

**Comment by Bonway** [comment]
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        self.arrayScreenshot = [NSMutableArray array];
    }
    return self;
}
我的demo里面有进行 初始化呀

**Comment by RaidenLin** [comment]
你把断点打在self.arrayScreenshot = [NSMutableArray array];这一行，然后运行，你会发现压根没走这一步

**Comment by Bonway** [comment]
你微信多少?我加您一下吧,方便吗?

**Comment by RaidenLin** [comment]
LZH123572
