### ISSUE TITLE
截图有问题的

### ISSUE THREAD

**Issue by Demonsword27** [Bonway/BBGestureBack#14]
pop的截图有问题  ![2861576550910_ pic](https://user-images.githubusercontent.com/17332298/70960774-f1259780-20ba-11ea-8b51-fb61d30d6b0d.jpg)    user item的字没了

**Comment by RaidenLin** [comment]
+1，其实不止这个问题，我在尝试毛玻璃穿透效果时，如果导航栏和底部TabBar设置为毛玻璃效果，会出现毛玻璃透明化

**Comment by Bonway** [comment]
iOS 13有点问题,我目前用的是 xcode10.3,没有问题,正在着手解决 适配问题
